name: CI pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-verision: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc
      - name: Run DVC pipeline
        env:
          DAGSHUB_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
        run: |
          dvc repro
      - name: Run model test
        env:
          DAGSHUB_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
        run: |
          python -m unittest test/model_test.py
